// ─── App Entry Point ───────────────────────────────────────────────
// Composes the CouchKit host pipeline:
//   AssetGate → GameHostProvider → ServerErrorGate → ScreenRouter
//
// Each layer guards a precondition before rendering children.
// This keeps the inner components blissfully unaware of boot concerns.

import React from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
import { GameHostProvider, useExtractAssets, useGameHost } from "@couch-kit/host";
import type { AssetManifest } from "@couch-kit/host";
import { hostReducer, createHostInitialState } from "./reducers/host-reducer.js";
import type { HostAction, HostGameState } from "./types/host-state.js";
import { RulesetPicker } from "./screens/RulesetPicker.js";
import { Lobby } from "./screens/Lobby.js";
import { GameTable } from "./screens/GameTable.js";

// ─── Asset Manifest ────────────────────────────────────────────────
// Generated by `couch-kit bundle`. Falls back to empty manifest for
// development builds where the bundled client hasn't been built yet.

let manifest: AssetManifest = { files: [] };
try {
  manifest = require("./www-manifest.json") as AssetManifest;
} catch {
  // Expected in dev — asset extraction will be a no-op.
}

// ─── AssetGate ─────────────────────────────────────────────────────

/**
 * Extracts bundled web assets from the APK before rendering children.
 * On Android, assets live inside the APK and must be copied to the
 * filesystem for the native HTTP server.
 */
function AssetGate({ children }: { readonly children: React.ReactNode }): React.JSX.Element {
  const { staticDir, loading, error } = useExtractAssets(manifest);

  if (error) {
    return (
      <View style={styles.center}>
        <Text style={styles.errorTitle}>Asset Extraction Failed</Text>
        <Text style={styles.errorBody}>{error}</Text>
      </View>
    );
  }

  if (loading) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color="#7c4dff" />
        <Text style={styles.loadingText}>Preparing assets...</Text>
      </View>
    );
  }

  return <HostProvider staticDir={staticDir}>{children}</HostProvider>;
}

// ─── HostProvider ──────────────────────────────────────────────────

/**
 * Wraps children with the CouchKit GameHostProvider, wiring up
 * the bridge reducer and initial state.
 */
function HostProvider({
  children,
  staticDir,
}: {
  readonly children: React.ReactNode;
  readonly staticDir: string | undefined;
}): React.JSX.Element {
  return (
    <GameHostProvider
      config={{
        reducer: hostReducer,
        initialState: createHostInitialState(),
        staticDir,
      }}
    >
      {children}
    </GameHostProvider>
  );
}

// ─── ServerErrorGate ───────────────────────────────────────────────

/**
 * Guards against CouchKit server startup errors.
 * Shows an error overlay if the server failed to start; otherwise
 * renders children.
 */
function ServerErrorGate({ children }: { readonly children: React.ReactNode }): React.JSX.Element {
  const { serverError } = useGameHost<HostGameState, HostAction>();

  if (serverError) {
    return (
      <View style={styles.center}>
        <Text style={styles.errorTitle}>Server Error</Text>
        <Text style={styles.errorBody}>{serverError.message}</Text>
      </View>
    );
  }

  return <>{children}</>;
}

// ─── ScreenRouter ──────────────────────────────────────────────────

/**
 * Reads the current screen from host state and renders the
 * appropriate screen component. Exhaustive switch ensures we
 * never miss a screen variant.
 */
function ScreenRouter(): React.JSX.Element {
  const { state } = useGameHost<HostGameState, HostAction>();

  switch (state.screen.tag) {
    case "ruleset_picker":
      return <RulesetPicker />;
    case "lobby":
      return <Lobby />;
    case "game_table":
      return <GameTable />;
  }
}

// ─── App Root ──────────────────────────────────────────────────────

export default function App(): React.JSX.Element {
  return (
    <View style={styles.root}>
      <AssetGate>
        <ServerErrorGate>
          <ScreenRouter />
        </ServerErrorGate>
      </AssetGate>
    </View>
  );
}

// ─── Styles ────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#121212",
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#121212",
    padding: 32,
  },
  loadingText: {
    color: "#e0e0e0",
    fontSize: 28,
    marginTop: 24,
    fontWeight: "300",
  },
  errorTitle: {
    color: "#ff5252",
    fontSize: 36,
    fontWeight: "700",
    marginBottom: 16,
  },
  errorBody: {
    color: "#b0b0b0",
    fontSize: 22,
    textAlign: "center",
    lineHeight: 32,
  },
});
